export enum ErrorCode {
  DATA_ERROR = 'DATA_ERROR',
  DATA_CONFLICT = 'DATA_CONFLICT',
  DATA_INVALID = 'DATA_INVALID',
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',

  NO_PERMISSION = 'NO_PERMISSION',
  PASSWORD_INVALID = 'PASSWORD_INVALID',

  VALIDATION_FAILED = 'VALIDATION_FAILED',

  GQL_FAILED = 'GQL_FAILED',
}
